# Generated by Django 3.2.8 on 2021-10-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_dailystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystock',
            name='rsi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='sma25',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='sma5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='sma75',
            field=models.FloatField(null=True),
        ),
    ]
