openapi: 3.0.0
info:
  version: 1.0.0
  title: 悪徳ペンギン商会 Stock API
  description: 米国株のスクリーニング API
servers:
  - url: 'http://localhost:8001'
paths:
  /api/stocks:
    get:
      description: 銘柄一覧を取得する
      parameters:
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Stock'
                  included:
                    type: array
                    items:
                      oneOf:
                        - $ref: "#/components/schemas/Market"
                        - $ref: "#/components/schemas/Sector"
                        - $ref: "#/components/schemas/DailyStock"
        '400':
          description: filter query id invald
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Stock:
      type: object
      required:
        - "id"
        - "type"
        - "attributes"
      properties:
        id:
          type: string
          example: "AAPL"
        type:
          type: string
          example: "Stock"
        attributes:
          type: object
          properties:
            name:
              type: string
              example: "Apple Inc. Common Stock"
            industry:
              type: string
              example: "Computer Manufacturing"
        links:
          type: object
          properties:
            self:
              type: string
              example: "https://localhost:8001/stocks/AAPL"
        relationships:
          type: object
          properties:
            market:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/MarketRelationship'
            sector:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/SectorRelationship'
            daily_atock:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/DailyStockRelationship'
    DailyStock:
      type: object
      required:
        - "id"
        - "type"
        - "attributes"
      properties:
        id:
          type: string
          example: "1"
        attributes:
          type: object
          properties:
            open:
              type: number
              format: "float"
              example: 20
            close:
              type: number
              format: "float"
              example: 20
            low:
              type: number
              format: "float"
              example: 20
            hight:
              type: number
              format: "float"
              example: 20
            amount_of_change:
              type: number
              format: "float"
              example: 20
            rsi:
              type: number
              format: "float"
              example: 20
            sma5:
              type: number
              format: "float"
              example: 20
            sma25:
              type: number
              format: "float"
              example: 20
            sma75:
              type: number
              format: "float"
              example: 20
        relationships:
          type: object
          properties:
            stock:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/StockRelationship'
    Market:
      type: object
      required:
        - "id"
        - "type"
        - "attributes"
      properties:
        id:
          type: string
          example: "1"
        type:
          type: string
          example: "market"
        attributes:
          type: object
          properties:
            name:
              type: string
              example: "NASDAQ"
    Sector:
      type: object
      required:
        - "id"
        - "type"
        - "attributes"
      properties:
        id:
          type: string
          example: "1"
        type:
          type: string
          example: "sector"
        attributes:
          type: object
          properties:
            name:
              type: string
              example: "Health Care"
    MarketRelationship:
      type: object
      required:
        - "id"
        - "type"
      properties:
        id:
          type: string
          example: "1"
        type:
          type: "string"
          example: "market"
    SectorRelationship:
      type: object
      required:
        - "id"
        - "type"
      properties:
        id:
          type: string
          example: "1"
        type:
          type: string
          example: "sector"
    DailyStockRelationship:
      type: object
      required:
        - "id"
        - "type"
      properties:
        id:
          type: string
          example: "1"
        type:
          type: string
          example: "daily_stock"
    StockRelationship:
      type: object
      required:
        - "id"
        - "type"
      properties:
        id:
          type: string
          example: "APPL"
        type:
          type: string
          example: "stock"
    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              ststus:
                type: number
                example: 400
              source:
                type: object
                properties:
                  pointer:
                    type: string
                    example: 'http://localhots:8001/api/stocks/APPL?page=10'
              title:
                type: string
                example: 'Bad Request'
              detail:
                type: string
                example: 'filter is invalid'
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
